# Generated by Django 3.2.5 on 2022-04-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvSerializers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='id',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='firstname',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
