# Generated by Django 3.2.5 on 2022-04-24 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_employee_ismarried'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isMarried',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
