# Generated by Django 3.2.5 on 2022-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_rename_ismarried_employee_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='married',
            field=models.BooleanField(default=False),
        ),
    ]
