# Generated by Django 3.2.5 on 2022-04-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_alter_employee_married'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='married',
        ),
    ]
